import type { Property } from "@/components/property-card"
import { PROPERTY_IMAGES } from "@/lib/stock-images"

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 1,
    title: "Casa con jardín en La Perla",
    location: "La Perla, Mar del Plata",
    price: "USD 185.000",
    type: "Venta",
    image: PROPERTY_IMAGES[0],
    bedrooms: 4,
    bathrooms: 2,
    area: "120 m²",
  },
  {
    id: 2,
    title: "Departamento 2 ambientes a estrenar",
    location: "Centro, Mar del Plata",
    price: "$ 95.000 / mes",
    type: "Alquiler",
    image: PROPERTY_IMAGES[1],
    bedrooms: 2,
    bathrooms: 1,
    area: "55 m²",
  },
  {
    id: 3,
    title: "Chalet en Playa Grande",
    location: "Playa Grande, Mar del Plata",
    price: "USD 220.000",
    type: "Venta",
    image: PROPERTY_IMAGES[2],
    bedrooms: 3,
    bathrooms: 2,
    area: "95 m²",
  },
  {
    id: 4,
    title: "PH con patio en Los Troncos",
    location: "Los Troncos, Mar del Plata",
    price: "USD 145.000",
    type: "Venta",
    image: PROPERTY_IMAGES[3],
    bedrooms: 3,
    bathrooms: 1,
    area: "78 m²",
  },
  {
    id: 5,
    title: "Casa amplia en Stella Maris",
    location: "Stella Maris, Mar del Plata",
    price: "$ 120.000 / mes",
    type: "Alquiler",
    image: PROPERTY_IMAGES[4],
    bedrooms: 5,
    bathrooms: 3,
    area: "180 m²",
  },
  {
    id: 6,
    title: "Departamento vista al mar",
    location: "Punta Mogotes, Mar del Plata",
    price: "USD 165.000",
    type: "Venta",
    image: PROPERTY_IMAGES[5],
    bedrooms: 2,
    bathrooms: 2,
    area: "72 m²",
  },
]
