export const OPERACIONES = [
  "Compra",
  "Venta",
  "Alquiler",
  "Alquiler para estudiantes",
] as const

export const TIPOS_PROPIEDAD = [
  "Casa/Chalet",
  "PH",
  "Departamento",
  "Terreno",
  "En block",
  "Desarrollo",
  "Fondo de comercio",
  "Local",
] as const

export const CIUDADES_BUENOS_AIRES: Record<string, string[]> = {
  "Mar del Plata": [
    "Todos",
    "Alem",
    "Alfar",
    "Bosque Peralta Ramos",
    "Camet",
    "Centro",
    "Chapadmalal",
    "Chauvin",
    "Colinas de Peralta Ramos",
    "Constitucion",
    "Del Viso",
    "Divino Rostro",
    "Don Bosco",
    "El Grosellar",
    "El Marquesado",
    "Estacion Camet",
    "Faro Norte",
    "General Pueyrredon",
    "Guemes",
    "La Perla",
    "La Florida",
    "Las Dalias",
    "Las Margaritas",
    "Libertad",
    "Los Acantilados",
    "Los Pinares",
    "Los Troncos",
    "Microcentro",
    "Mogotes",
    "Nuevo Golf",
    "Once de Septiembre",
    "Parque Camet",
    "Parque Luro",
    "Parque Palermo",
    "Peralta Ramos",
    "Playa Grande",
    "Playa Serena",
    "Plaza Mitre",
    "Pompeya",
    "Pueyrredon",
    "Punta Mogotes",
    "Remedios de Escalada",
    "Residencial",
    "San Carlos",
    "San Cayetano",
    "San Jose",
    "San Juan",
    "San Martin",
    "Santa Celina",
    "Santa Rita",
    "Sierra de los Padres",
    "Stella Maris",
    "Tierra Alta",
    "Zacagnini",
    "Zurich",
  ],
  "La Plata": [
    "Todos",
    "Abasto",
    "Barrio Hipódromo",
    "Barrio Norte",
    "Berisso",
    "Centro",
    "City Bell",
    "Ensenada",
    "Gonnet",
    "Hernandez",
    "Los Hornos",
    "Olmos",
    "Ringuelet",
    "San Carlos",
    "Tolosa",
    "Villa Elisa",
    "Villa Elvira",
  ],
  "Bahia Blanca": [
    "Todos",
    "Aldea Romana",
    "Barrio Noroeste",
    "Barrio Universitario",
    "Bella Vista",
    "Centro",
    "Grünbein",
    "Ingeniero White",
    "La Falda",
    "Las Villas",
    "Loma Paraguaya",
    "Napostá",
    "Patagonia",
    "Palihue",
    "Sanchez Elia",
    "Tiro Federal",
    "Villa Bordeu",
    "Villa Mitre",
  ],
  "Tandil": [
    "Todos",
    "Centro",
    "Cerro Leones",
    "Don Bosco",
    "Golf",
    "La Movediza",
    "Las Tunitas",
    "Palermo",
    "Villa Aguirre",
    "Villa del Lago",
    "Villa Italia",
  ],
  "Pinamar": [
    "Todos",
    "Centro",
    "Frontera Norte",
    "La Herradura",
    "Las Gaviotas",
    "Montecarlo",
    "Ostende",
    "Pinamar Norte",
    "Valeria del Mar",
  ],
  "Villa Gesell": [
    "Todos",
    "Centro",
    "Barrio Norte",
    "Barrio Sur",
    "Las Gaviotas",
    "Mar Azul",
    "Mar de las Pampas",
  ],
  "Necochea": [
    "Todos",
    "Centro",
    "Costa Bonita",
    "El Bosque",
    "Quequen",
    "Punta Negra",
  ],
  "Miramar": [
    "Todos",
    "Centro",
    "Mar del Sud",
    "Vivero Dunícola",
  ],
  "San Nicolas de los Arroyos": [
    "Todos",
    "Centro",
    "La Ribera",
    "Barrio SOMISA",
    "Barrio Savio",
  ],
  "Junin": [
    "Todos",
    "Centro",
    "Barrio Hospital",
    "Barrio Las Morochas",
    "Pueblo Nuevo",
  ],
  "Olavarria": [
    "Todos",
    "Centro",
    "Loma Negra",
    "Pueblo Nuevo",
    "Sierra Chica",
    "Sierras Bayas",
  ],
  "Pergamino": [
    "Todos",
    "Centro",
    "Barrio Acevedo",
    "Barrio Centenario",
  ],
  "Lujan": [
    "Todos",
    "Centro",
    "Open Door",
    "Torres",
    "Villa del Parque",
  ],
  "Zarate": [
    "Todos",
    "Centro",
    "Lima",
    "Barrio COPISA",
    "Escalada",
  ],
  "Campana": [
    "Todos",
    "Centro",
    "Los Cardales",
    "Otamendi",
  ],
  "San Pedro": [
    "Todos",
    "Centro",
    "Barrio Santa Lucia",
    "Gobernador Castro",
    "Rio Tala",
  ],
  "Dolores": [
    "Todos",
    "Centro",
    "Sevigne",
  ],
  "Chascomus": [
    "Todos",
    "Centro",
    "Barrio La Noria",
    "Lagunas Encadenadas",
  ],
  "Azul": [
    "Todos",
    "Centro",
    "Cacharí",
    "Chillar",
  ],
  "Tres Arroyos": [
    "Todos",
    "Centro",
    "Claromecó",
    "Orense",
    "Reta",
  ],
}

export const CIUDADES_NOMBRES = Object.keys(CIUDADES_BUENOS_AIRES)

export const AMBIENTES = Array.from({ length: 15 }, (_, i) => i + 1)
